# Require `bevy_ecs::children!` to use `[]` braces, instead of `()` or `{}`.
standard-macro-braces = [{ name = "children", brace = "[" }]
# Disable lints for if-let chains to ensure `stable` compatibility.
# See https://github.com/rust-lang/rust-clippy/issues/14825
msrv = "1.87"
# Types can get complex in Bevy
type-complexity-threshold = 400
